pkt_limit: 20
batch_size: 12
pcap_folder_path: "../ProxyData/local_pcaps"
csv_path: "~/Documents/ProxyData/subset_v2_info.csv"
background_distributions_path: "configs/background_distributions.json"
output_path: "data_2"

experiments:



  # - name: "ta_tp"
  #   feature_extractor: "TAFeatureExtractor"
  #   attacks:
  #     - name: "br"
  #       params: {}
  #     - name: "tp"
  #       params:
  #         n_packets_to_pad: 10
  #         pad_size: 150

  # - name: "ta_pr"
  #   feature_extractor: "TAFeatureExtractor"
  #   attacks:
  #     - name: "br"
  #       params: {}
  #     - name: "pr"
  #       params:
  #         split_threshold: 1000
  #         max_splits: 3
  #         min_pkt_size: 128

  # - name: "ta_ipd"
  #   feature_extractor: "TAFeatureExtractor"
  #   attacks:
  #     - name: "br"
  #       params: {}
  #     - name: "ipd"
  #       params:
  #         n_packets_to_jitter: 15
  #         max_delay_s: 0.02

  # - name: "ta_decorr"
  #   feature_extractor: "TAFeatureExtractor"
  #   attacks:
  #     - name: "br"
  #       params: {}
  #     - name: "decorr"
  #       params: {}

  - name: "corr_decorr"
    feature_extractor: "CorrFeatureExtractor"
    attacks:
      - name: "br"
        params: {}
      - name: "decorr"
        params: {}

  # - name: "slt_decorr"
  #   feature_extractor: "SLTFeatureExtractor"
  #   attacks:
  #     - name: "br"
  #       params: {}
  #     - name: "decorr"
  #       params: {}
      # - name: "pr"
      #   params:
      #     split_threshold: 1000
      #     max_splits: 3
      #     min_pkt_size: 128

  # - name: "slt_tp"
  #   feature_extractor: "SLTFeatureExtractor"
  #   attacks:
  #     - name: "br"
  #       params: {}
  #     - name: "tp"
  #       params:
  #         n_packets_to_pad: 10
  #         pad_size: 150

  # - name: "slt_ipd"
  #   feature_extractor: "SLTFeatureExtractor"
  #   attacks:
  #     - name: "br"
  #       params: {}
  #     - name: "ipd"
  #       params:
  #         n_packets_to_jitter: 15
  #         max_delay_s: 0.02


  # - name: "corr_br"
  #   feature_extractor: "CorrFeatureExtractor"
  #   attacks:
  #     - name: "br"
  #       params: {}


  # - name: "corr_pr"
  #   feature_extractor: "CorrFeatureExtractor"
  #   attacks:
  #     - name: "br"
  #       params: {}
  #     - name: "pr"
  #       params:
  #         split_threshold: 1000
  #         max_splits: 3
  #         min_pkt_size: 128

  # - name: "corr_tp"
  #   feature_extractor: "CorrFeatureExtractor"
  #   attacks:
  #     - name: "br"
  #       params: {}
  #     - name: "tp"
  #       params:
  #         n_packets_to_pad: 10
  #         pad_size: 150

  # - name: "corr_ipd"
  #   feature_extractor: "CorrFeatureExtractor"
  #   attacks:
  #     - name: "br"
  #       params: {}
  #     - name: "ipd"
  #       params:
  #         n_packets_to_jitter: 15
  #         max_delay_s: 0.02
      


